### ISSUE TITLE
Paging not working

### ISSUE THREAD

**Issue by bureaublanc** [fw4-bvba/whise-api#1]
When you make a call and the response contains more than the limit of 50 you do get all the items.
When you loop over the items at position 51 you get item 1 again.
How to use the pagination should be in the docs.

**Comment by Fyrts** [comment]
Thanks for the report, I was able to reproduce the problem.
I've pushed a new release that resolves the issue. Could you update the package and confirm if it's working?

**Comment by bureaublanc** [comment]
Thanks for the fix. Now the response is returning the limit of 50 items.
Can you please explain how the paging should be used?

**Comment by Fyrts** [comment]
Which endpoint are you having trouble with?

Pagination is taken care of automatically, and simply traversing the response should suffice. For example, the following would traverse over all estates with category id 1, no matter how many pages the result might contain:
```php
foreach ($api->estates()->list([
    'CategoryIds' => [1],
]) as $estate) {
    echo $estate->id . PHP_EOL;
}
```

**Comment by bureaublanc** [comment]
Let's say on page 1 we list 50 properties, and if we scroll to the end of the page an ajax call triggers to get the next 50 (or even a classic paging system with links (prev 1 2 3 next). It's not clear to me how I can get that second 'page'...

**Comment by Fyrts** [comment]
That makes sense. At this time, we haven't implemented manual pagination, as we've had no need for it ourselves yet. I'll see if I can add it sometime in the next couple of days. Will keep you posted!

**Comment by bureaublanc** [comment]
Cool, thanks for your feedback. Looking forward to it!

**Comment by Fyrts** [comment]
I've implemented manual pagination with the latest release. Refer to the documentation for information on how to use it. Let me know if this solves your issue.

**Comment by bureaublanc** [comment]
Great! Works like a charm. Thanks again.
