### ISSUE TITLE
Filter and sorting not working?

### ISSUE THREAD

**Issue by freshface** [fw4-bvba/whise-api#11]
Hi

I have this example:

```
 $sorting =  [
                "Ascending" => false,
                "Field" => "price"
                ];

              $filter = [
                'PurposeStatusIds' => [3],
              ];

            $result = $api->estates()->list($filter, $sorting);
```

But i always get the same results.
Filter and sorting does not seem to work.

Am i doing something wrong?

**Comment by freshface** [comment]
If you pass the filter and sorting like this it works `            $result = $api->estates()->list(['Filter' => $filter, 'Sort' => $sorting]);
`

**Comment by Fyrts** [comment]
The `Sort` parameter accepts an array of objects. Try this:

```php
$sorting =  [
    [
        "Ascending" => false,
        "Field" => "price"
    ]
];

$filter = [
    'PurposeStatusIds' => [3],
];

$result = $api->estates()->list($filter, $sorting);
```

I've made a tweak in 1.5.3 to support passing a single sorting parameter as an associative array to `estates()->list()`, so updating the package should fix your issue as well.
