### ISSUE TITLE
Redis caching

### ISSUE THREAD

**Issue by bureaublanc** [fw4-bvba/whise-api#2]
What would be the best way to add the response of eg estates()->list() to Redis cache? The resulting list of objects is not serializable nor json encodable, which is necessary to be able to insert it into a Redis db.

**Comment by Fyrts** [comment]
I've implemented caching in the latest release. That should allow you to use any PSR-6 compatible Redis cache adapter. Refer to the readme for more information and an example.

As for json encoding responses of estates()->list(), keep in mind that the method returns an object that implements automatic pagination, and only buffers a single page of results at a time. Loading the entire dataset into memory for encoding could easily cause memory issues. If you'd still like to implement your own caching through json encoding, I would suggest using manual pagination, and encoding the resulting pages separately (which support json serialisation in the latest release).
