### ISSUE TITLE
Handle empty resultset

### ISSUE THREAD

**Issue by bureaublanc** [fw4-bvba/whise-api#3]
How do I have to handle an empty resultset?

eg:
$estates = $api->estates()->list($filter, $sorting);
echo $estates->count();

This returns PHP Fatal error:  Uncaught Whise\Api\Exception\PaginationException: Unable to retrieve total item count of endpoint that does not return totalCount

**Comment by Fyrts** [comment]
It seems that the Whise API no longer returns a totalCount value for empty results. I've updated the implementation to assume a value of zero when it's missing.

**Comment by bureaublanc** [comment]
Thanks again for the quick fix!
