### ISSUE TITLE
Fatal Error after timeout

### ISSUE THREAD

**Issue by bureaublanc** [fw4-bvba/whise-api#5]
When adding a contact (via endpoint $api->contacts()->create($parameters);) the contact is added in whise but php throws a fatal error:

AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught GuzzleHttp\\Exception\\ConnectException: cURL error 28: Operation timed out after 2000 milliseconds with 0 bytes received (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) in .../vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:200\nStack trace:\n#0 .../vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(155): GuzzleHttp\\Handler\\CurlFactory::createRejection()\n#1 .../vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(105): GuzzleHttp\\Handler\\CurlFactory::finishError()\n#2 .../vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(43): GuzzleHttp\\Handler\\CurlFactory::finish()\n#3 ../vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(28): GuzzleHttp\\Handler\\Curl...'

Setting timeout and exceptions (see below) doesn't solve the problem.
$api = new WhiseApi(TOKEN, ['timeout' => 0, 'exceptions' => false]);

**Comment by Fyrts** [comment]
Unfortunately, the Whise API has been rather slow and unreliable recently. I had created a commit that increased the default timeout and added the ability to pass HTTP client options, but hadn't created a release for it yet. I've now pushed release 1.2.3 which should allow you to take advantage of the changes.

**Comment by bureaublanc** [comment]
I'm on the latest release but keep getting timeouts from time to time. What client options would you suggest?

**Comment by Fyrts** [comment]
We've been seeing some inconsistent response times as well. I believe the best course of action right now would be to remove the default timeout. I've tagged a new release which should restore Guzzle's default (indefinite) timeout. Should you nonetheless still run into any timeouts, it might be worth looking into the various timeout parameters available for Guzzle. If you do, let me know what you find out.
