### ISSUE TITLE
totalCount issue with offices list

### ISSUE THREAD

**Issue by harkor** [fw4-bvba/whise-api#7]
Hello,

I have a little problem with offices list api, it's seems an API bug but Whise Helpdesk answer literally "It's not a bug it's a feature"

```
$params = [
    'OfficeIds' = [] // <== Insert some compatible id's from your own account
];

$result = $this->whise_api->admin()->offices()->list($params);

var_dump(sizeof($result);

```
The problem is API return wrong totalCount if we set params and sizeof return the totalCount give by API.

If I made a foreach I have a PHP Notice.

Response from Helpdesk
```
You have only 3 offices activated on your account and 1 your own test account .
So in total you have 4 offices activated on your account.
```

On my case, my example return 3 offices but totalCount return 4.

They answer totalCount isn't total returned on result but total on my account.

If I take an example response from estates list, totalCount return total items in response.

Maybe we can all report this bug to have consideration or we need adapt ?

**Comment by Fyrts** [comment]
I am able to reproduce the issue, agree that the behaviour is unexpected, and have asked Whise for clarification. If they confirm that this functionality is intentional, I will update the package to correctly handle the inconsistent responses.

**Comment by Fyrts** [comment]
I haven't heard back from Whise yet, but I've committed a change that would transparently support the lack of pagination when using the OfficeIds parameter. Once I receive confirmation, I'll tag it for release. For the time being, you could temporarily implement the change by running `composer require fw4/whise-api:dev-main`

**Comment by harkor** [comment]
Thanks,

we have problem with all filters sent to api with offices list, for example, on my project, I use ClientId.

It was easier too explain issue with officeids but clientid return the same issue.

I don't try with OfficeName but I think it's same.

**Comment by Fyrts** [comment]
You're entirely right, I overlooked the other parameters. I've commited an update to support these as well.

While looking into this issue I've also noticed that Whise's pagination implementation on admin/offices/list differs from the rest of the API. More specifically, on this endpoint the Page:Offset parameter is not interpreted as an offset, but as a page number instead, breaking our pagination implementation. I have once again asked Whise for clarification of the undocumented behaviour, and will update the issue once I know more.

**Comment by harkor** [comment]
I work with Whise system since 7 years (exclusively with the old webservices) and with experience, if at a time they din't respond about an issue, they working on it without communication with external developers.

Anyway, thank you for your work with this project, it's saving me a lot of development time.

**Comment by Fyrts** [comment]
I've received feedback from Whise that the inconsistent pagination has recently been fixed. Testing seems to confirm this. Should anyone run into this bug again, feel free to reopen the issue.
