### ISSUE TITLE
Bad request when sending https://api.whise.eu/v1/estates/list

### ISSUE THREAD

**Issue by fvanhove** [fw4-bvba/whise-api#8]
Hey, 

I noticed Whise changed the api and now has a stricter policy for arrays. 

It no longer seems to accept: 

```		
"DisplayStatusIds":{
  "Offline":1,
  "Online":2,
  "EstateOfTheMonth":3,
  "Realisations":4,
  "OnlineWebsiteOnly":5
},
```

but instead only accepts stricter arrays like such:

```
"DisplayStatusIds":[1,2,3,4,5,6]
```

The get function on  Whise\Api\Endpoints\Estates seems to be affected by this. 
Changing the enums to values only seems to resolve the issue. 
```
$estates = $this->list(array_merge([
    'EstateIds' => [$id],
    'StatusIds' => array_values(Enums\Status::all()),
    'DisplayStatusIds' => array_values(Enums\DisplayStatus::all()),
], $filter), null, $field)->page(0, 1);
```

**Comment by Fyrts** [comment]
I had recently noticed the same issue, and had a fix in the works (fe7a630349a8fc604bda8d6bda4c5605d2ff2bc8). I was hoping for Whise to resolve #7 before pushing a new release, but I'm not getting much feedback from them. I've gone ahead and released 1.4.0, which should resolve your issue. Can you confirm?
